# -*- coding: utf-8 -*-
"""Manipulasi String.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11yq6vt6oHo5Iz8gpGYPmLiRAZpI6W1ou

**String**
"""

nama = 'Lutfiah Insani Nabila'
asal = "Indonesia"

print(nama)

print(asal)

"""**Manipulasi String**"""

print(nama, asal)

print(nama + asal)

print("Hallo, nama saya",nama)

print("Hallo, nama saya",nama, "asal saya dari", asal)

data_lengkap = nama + asal

print(data_lengkap)

"""**String + Non String**"""

asal_kota = "Bandar Lampung"
kode_pos = 35411

asal_kota_kode_pos = asal_kota + str(kode_pos)
print(asal_kota_kode_pos)

asal_kota_x3 = asal_kota * 3
print(asal_kota_x3)

