# -*- coding: utf-8 -*-
"""Tipe Data Casting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Aj-Pn4RhPKf6KyxCennHzHZZD76zPsuD

**Memeriksa Jenis Tipe Data**
"""

nama = 'Budi'
usia = 20
lajang = True

print(type(nama))
print(type(usia))
print(type(lajang))

"""**Konversi Tipe Data**"""

usia = input('Masukkan usia anda: ')

print(type(usia))

panjang = input('Masukkan panjang: ')
lebar = input('Masukkan lebar: ')

luas = int(panjang) * int(lebar)

print('luas =', luas)

"""**Konversi Tipe Data Secara Eksplisit**

Untuk tipe data primitif, kita bisa memanggil fungsi berikut:
- int() - untuk konversi data ke Integer
- float() - umtuk konversi data ke float
- bool() - untuk konversi data ke bool
- str() - untuk konversi data ke string

Untuk tipe data tergolong tipe data canggih (atau buatan), contoh:
- list() - untuk list
- set() - untuk set
- tuple() - untuk tuple

**Konversi Tipe Data Secara Implisit**
"""

a = 10 / 2
print(type(a))

b = 1 / 2
print(type(b))

kata = 'Jeruk' * 5
print(kata)

"""**Konversi String ke Numerik**"""

panjang = int(input('Masukkan panjang: '))
lebar = float(input('Masukkan lebar: '))

print('Luas =', panjang * lebar)

"""**Konversi String ke Numerik**"""

nama ='Wudi'
tahun_lahir = 2000

print(nama +' lahir di tahun ' + str(tahun_lahir))